# Generated by Django 6.0.5 on 2026-05-24 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid 10 digit mobile number', regex='^[0-9]{10}$')]),
        ),
    ]
