# Generated by Django 6.0.5 on 2026-05-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_donor_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
