# Generated by Django 6.0.5 on 2026-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_bloodrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
